"""initial schema

Revision ID: 39e92656b3c4
Revises: 
Create Date: 2026-06-26 16:57:55.030726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39e92656b3c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('monogram', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('vertical', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bank_id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('discount_type', sa.String(), nullable=False),
    sa.Column('discount_value', sa.Float(), nullable=False),
    sa.Column('max_discount_cap', sa.Integer(), nullable=True),
    sa.Column('min_spend', sa.Integer(), nullable=True),
    sa.Column('applicable_days', sa.JSON(), nullable=False),
    sa.Column('time_window', sa.String(), nullable=True),
    sa.Column('cities', sa.JSON(), nullable=False),
    sa.Column('eligible_networks', sa.JSON(), nullable=False),
    sa.Column('eligible_tiers', sa.JSON(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=False),
    sa.Column('scope_note', sa.String(), nullable=True),
    sa.Column('exclusions', sa.String(), nullable=True),
    sa.Column('terms_url', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('last_verified', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offers_bank_id'), ['bank_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_last_verified'), ['last_verified'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offers_status'))
        batch_op.drop_index(batch_op.f('ix_offers_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_offers_last_verified'))
        batch_op.drop_index(batch_op.f('ix_offers_bank_id'))

    op.drop_table('offers')
    op.drop_table('merchants')
    op.drop_table('banks')
    # ### end Alembic commands ###
