import type { Bank, Offer } from "./types";

// ---------------------------------------------------------------------------
// SAMPLE DATA — for development and design only.
// These offers are illustrative and NOT verified against any bank. The real
// dataset will come from the ingestion pipeline + human review (see docs/).
// ---------------------------------------------------------------------------

export const banks: Bank[] = [
  { id: "meezan", name: "Meezan Bank", monogram: "MZN", color: "#0a7d4d" },
  { id: "hbl", name: "HBL", monogram: "HBL", color: "#00855b" },
  { id: "ubl", name: "UBL", monogram: "UBL", color: "#1763a6" },
  { id: "alfalah", name: "Bank Alfalah", monogram: "BAF", color: "#9b1b30" },
  { id: "scb", name: "Standard Chartered", monogram: "SC", color: "#0473ea" },
  { id: "faysal", name: "Faysal Bank", monogram: "FSL", color: "#1f7a52" },
  { id: "mcb", name: "MCB Bank", monogram: "MCB", color: "#16794c" },
];

export const cities = ["Karachi", "Lahore", "Islamabad", "Rawalpindi"];

export const offers: Offer[] = [
  {
    id: "ofr-001",
    bankId: "meezan",
    merchant: { id: "m-kolachi", name: "Kolachi", category: "BBQ & Pakistani", vertical: "restaurant" },
    title: "15% off the total bill at Kolachi",
    description:
      "Get 15% off your total bill at Kolachi when you pay with an eligible Meezan card. Valid on dine-in and takeaway.",
    discountType: "percentage",
    discountValue: 15,
    maxDiscountCap: 3000,
    applicableDays: ["All"],
    cities: ["Karachi"],
    eligibleNetworks: ["Visa", "Mastercard"],
    eligibleTiers: ["Gold", "Platinum", "Signature"],
    validTo: "2026-12-31",
    termsUrl: "https://www.meezanbank.com/offers",
    sourceUrl: "https://www.meezanbank.com/discounts",
    lastVerified: "2026-06-22",
    status: "active",
  },
  {
    id: "ofr-002",
    bankId: "hbl",
    merchant: { id: "m-kababjees", name: "Kababjees", category: "BBQ & Grill", vertical: "restaurant" },
    title: "20% off on Tuesdays at Kababjees",
    description:
      "Enjoy 20% off your bill every Tuesday with HBL CreditCards. The perfect midweek treat.",
    discountType: "percentage",
    discountValue: 20,
    minSpend: 2000,
    applicableDays: ["Tue"],
    cities: ["Karachi", "Lahore"],
    eligibleNetworks: ["Visa", "Mastercard", "UnionPay"],
    eligibleTiers: ["Platinum", "World", "World Elite"],
    validTo: "2026-09-30",
    exclusions: "Not valid on public holidays.",
    termsUrl: "https://www.hbl.com/offers/kababjees",
    sourceUrl: "https://www.hbl.com/personal/cards/discounts",
    lastVerified: "2026-06-18",
    status: "active",
  },
  {
    id: "ofr-003",
    bankId: "ubl",
    merchant: { id: "m-aylanto", name: "Café Aylanto", category: "Continental & Fine Dining", vertical: "restaurant" },
    title: "Buy 1 Get 1 on main courses",
    description:
      "Buy one main course and get the second free at Café Aylanto, exclusively for UBL Signature cardholders.",
    discountType: "bogo",
    discountValue: 0,
    applicableDays: ["Mon", "Tue", "Wed", "Thu"],
    timeWindow: "Dinner · 7pm–11pm",
    cities: ["Lahore", "Karachi"],
    eligibleNetworks: ["Visa", "Mastercard"],
    eligibleTiers: ["Signature", "Infinite"],
    validTo: "2026-08-15",
    scopeNote: "Valid on à la carte main courses only.",
    exclusions: "Not valid on weekends & public holidays.",
    termsUrl: "https://www.ubldigital.com/offers/aylanto",
    sourceUrl: "https://www.ubldigital.com/Personal/Cards/Discounts",
    lastVerified: "2026-06-24",
    status: "active",
  },
  {
    id: "ofr-004",
    bankId: "alfalah",
    merchant: { id: "m-howdy", name: "Howdy", category: "American & Burgers", vertical: "restaurant" },
    title: "Rs 500 off on orders above Rs 2,500",
    description:
      "Flat Rs 500 off when you spend Rs 2,500 or more at Howdy with Bank Alfalah cards.",
    discountType: "flat",
    discountValue: 500,
    minSpend: 2500,
    applicableDays: ["All"],
    cities: ["Islamabad", "Rawalpindi"],
    eligibleNetworks: ["Visa", "Mastercard", "UnionPay"],
    eligibleTiers: ["Gold", "Platinum", "Titanium"],
    validTo: "2026-07-20",
    termsUrl: "https://www.bankalfalah.com/offers/howdy",
    sourceUrl: "https://www.bankalfalah.com/personal-banking/cards/offers",
    lastVerified: "2026-06-21",
    status: "active",
  },
  {
    id: "ofr-005",
    bankId: "scb",
    merchant: { id: "m-okra", name: "OKRA", category: "Mediterranean", vertical: "restaurant" },
    title: "25% off for Standard Chartered Priority",
    description:
      "Standard Chartered Priority cardholders get 25% off the total bill at OKRA. Dine-in only.",
    discountType: "percentage",
    discountValue: 25,
    maxDiscountCap: 5000,
    applicableDays: ["All"],
    cities: ["Karachi"],
    eligibleNetworks: ["Visa", "Mastercard"],
    eligibleTiers: ["Infinite", "World Elite"],
    validTo: "2026-11-30",
    scopeNote: "Dine-in only.",
    termsUrl: "https://www.sc.com/pk/offers/okra",
    sourceUrl: "https://www.sc.com/pk/promotions",
    lastVerified: "2026-06-15",
    status: "active",
  },
  {
    id: "ofr-006",
    bankId: "faysal",
    merchant: { id: "m-chaayekhana", name: "Chaaye Khana", category: "Café & Desserts", vertical: "restaurant" },
    title: "10% off on desserts",
    description:
      "Sweeten your day with 10% off the dessert menu at Chaaye Khana using Faysal Bank cards.",
    discountType: "percentage",
    discountValue: 10,
    applicableDays: ["All"],
    cities: ["Islamabad", "Lahore"],
    eligibleNetworks: ["Visa", "PayPak"],
    eligibleTiers: ["Debit", "Classic", "Gold"],
    validTo: "2026-10-10",
    scopeNote: "Valid on desserts only.",
    termsUrl: "https://www.faysalbank.com/offers/chaaye-khana",
    sourceUrl: "https://www.faysalbank.com/en/personal/cards/discounts",
    lastVerified: "2026-06-12",
    status: "active",
  },
  {
    id: "ofr-007",
    bankId: "mcb",
    merchant: { id: "m-bundukhan", name: "Bundu Khan", category: "BBQ & Pakistani", vertical: "restaurant" },
    title: "5% cashback at Bundu Khan",
    description:
      "Earn 5% cashback on your bill at Bundu Khan when you pay with MCB cards. Cashback credited within 30 days.",
    discountType: "cashback",
    discountValue: 5,
    maxDiscountCap: 1500,
    applicableDays: ["All"],
    cities: ["Lahore", "Karachi", "Islamabad"],
    eligibleNetworks: ["Visa", "Mastercard", "PayPak"],
    eligibleTiers: ["Gold", "Platinum"],
    validTo: "2026-12-15",
    termsUrl: "https://www.mcb.com.pk/offers/bundu-khan",
    sourceUrl: "https://www.mcb.com.pk/personal/cards/discounts",
    lastVerified: "2026-06-23",
    status: "active",
  },
  {
    id: "ofr-008",
    bankId: "meezan",
    merchant: { id: "m-xanders", name: "Xander's", category: "Continental", vertical: "restaurant" },
    title: "Weekend brunch — 20% off",
    description:
      "20% off the weekend brunch menu at Xander's for Meezan Visa Platinum and above.",
    discountType: "percentage",
    discountValue: 20,
    applicableDays: ["Sat", "Sun"],
    timeWindow: "Brunch · 11am–4pm",
    cities: ["Lahore", "Islamabad"],
    eligibleNetworks: ["Visa"],
    eligibleTiers: ["Platinum", "Signature", "Infinite"],
    validTo: "2026-08-31",
    scopeNote: "Valid on the brunch menu only.",
    termsUrl: "https://www.meezanbank.com/offers/xanders",
    sourceUrl: "https://www.meezanbank.com/discounts",
    lastVerified: "2026-06-19",
    status: "active",
  },
  {
    id: "ofr-009",
    bankId: "hbl",
    merchant: { id: "m-tooso", name: "Tooso", category: "Italian & Pizza", vertical: "restaurant" },
    title: "15% off at Tooso",
    description:
      "15% off the total bill at Tooso with HBL debit and credit cards. Dine-in and delivery.",
    discountType: "percentage",
    discountValue: 15,
    applicableDays: ["All"],
    cities: ["Karachi"],
    eligibleNetworks: ["Visa", "Mastercard", "PayPak"],
    eligibleTiers: ["Debit", "Classic", "Gold", "Platinum"],
    validTo: "2026-07-05",
    termsUrl: "https://www.hbl.com/offers/tooso",
    sourceUrl: "https://www.hbl.com/personal/cards/discounts",
    lastVerified: "2026-05-02",
    status: "active",
  },
  {
    id: "ofr-010",
    bankId: "ubl",
    merchant: { id: "m-kfc", name: "KFC", category: "Fast Food", vertical: "restaurant" },
    title: "Rs 300 off on orders above Rs 1,500",
    description:
      "Flat Rs 300 off at KFC nationwide when you spend Rs 1,500 or more with UBL cards.",
    discountType: "flat",
    discountValue: 300,
    minSpend: 1500,
    applicableDays: ["All"],
    cities: ["Karachi", "Lahore", "Islamabad", "Rawalpindi"],
    eligibleNetworks: ["Visa", "Mastercard", "UnionPay", "PayPak"],
    eligibleTiers: ["Debit", "Classic", "Gold", "Platinum"],
    validTo: "2026-09-01",
    termsUrl: "https://www.ubldigital.com/offers/kfc",
    sourceUrl: "https://www.ubldigital.com/Personal/Cards/Discounts",
    lastVerified: "2026-06-25",
    status: "active",
  },
  {
    id: "ofr-011",
    bankId: "scb",
    merchant: { id: "m-monal", name: "Monal", category: "Pakistani & BBQ", vertical: "restaurant" },
    title: "18% off with a view at Monal",
    description:
      "18% off your bill at Monal Islamabad for Standard Chartered cardholders.",
    discountType: "percentage",
    discountValue: 18,
    maxDiscountCap: 4000,
    applicableDays: ["All"],
    cities: ["Islamabad"],
    eligibleNetworks: ["Visa", "Mastercard"],
    eligibleTiers: ["Platinum", "Signature", "Infinite"],
    validTo: "2026-10-31",
    termsUrl: "https://www.sc.com/pk/offers/monal",
    sourceUrl: "https://www.sc.com/pk/promotions",
    lastVerified: "2026-06-10",
    status: "unverified",
  },
  {
    id: "ofr-012",
    bankId: "alfalah",
    merchant: { id: "m-coliseum", name: "Coliseum Cinema", category: "Entertainment", vertical: "retail" },
    title: "2 tickets for the price of 1",
    description:
      "Buy one cinema ticket and get one free at Coliseum with Bank Alfalah credit cards. Weekdays only.",
    discountType: "bogo",
    discountValue: 0,
    applicableDays: ["Mon", "Tue", "Wed", "Thu"],
    cities: ["Lahore"],
    eligibleNetworks: ["Visa", "Mastercard"],
    eligibleTiers: ["Gold", "Platinum", "Titanium"],
    validTo: "2026-07-31",
    exclusions: "Not valid on weekends, public holidays, or premium screenings.",
    termsUrl: "https://www.bankalfalah.com/offers/coliseum",
    sourceUrl: "https://www.bankalfalah.com/personal-banking/cards/offers",
    lastVerified: "2026-06-20",
    status: "active",
  },
];

export const bankById = (id: string): Bank | undefined =>
  banks.find((b) => b.id === id);
